version: "3.9"
services:
    vodserver:
        image: gcc:4.9
        build: .
        volumes:
            - .:/vodserver
        ports:
            - "8080:8080"
        command: "./build/vodserver 8080"
